### PR TITLE
The status is already "Ready" status. If  we call onPlayerStateChange…

### PR DESCRIPTION
**Pull request by chirs1985**
…d again, it will cause top layer execute the On Ready twice.

### CODE REVIEW

**Comment by ojw28** [comment]
I'm not sure what the intention is here, but this doesn't look right.

**Comment by chirs1985** [comment]
I signed it!

**Comment by ojw28** [comment]
Please see comment above.

**Comment by chirs1985** [comment]
Sorry, I don't understand the sentence meaning. ---> "Please see comment above."

**Comment by ojw28** [comment]
It's working as intended that the listener is invoked when playWhenReady changes. It's even explicitly documented that way [here](https://google.github.io/ExoPlayer/doc/reference/com/google/android/exoplayer/ExoPlayer.Listener.html#onPlayerStateChanged(boolean,%20int)). So I don't understand what this change is actually trying to achieve. It looks like it's removing correct behavior.

**Comment by chirs1985** [comment]
I think whether it need to add one "running" status? Otherwise the status is always ready, not onPlayerStateChanged

**Comment by ojw28** [comment]
Closing this because I still don't understand what it is. I'm almost certain this isn't necessary, and no-one else has reported any issues with how the listener works.

**Comment by chirs1985** [comment]
Because our player meet this kind issue, we already add a check function to prevent execute some important function twice. I don't think it is a good method that add a check function at top layer program. Architecture should be reliability.

**Pull request closed without merging**
