### PR TITLE
DefaultUriDataSource: enable udp scheme support

### PR DESCRIPTION
**Pull request by gpinigin**

### CODE REVIEW

**Comment by ojw28** [comment]
I don't think we really want to do this. The UDP data source isn't fully featured (e.g. doesn't support range requests), and I don't think our extractors recover correctly from packet loss either. It seems quite disingenuous to claim UDP support by default where in reality it's more of a "best effort" kind of thing.

**Comment by gpinigin** [comment]
Got it, but there is need a better error handling for unknown schemes.

**Comment by ojw28** [comment]
What's the failure mode now, exactly, and what does "better" mean? What would you like the failure mode to be?

**Comment by gpinigin** [comment]
1. DefaultUriDataSource assumes that default datasource is HTTP-based
2. DefaultUriDataSource uses DefaultHttpDataSource for any unknown scheme
3. DefaultUriDataSource indirectly throws exceptions related to HTTP protocol when trying to connect/read 

From my point of view DefaultUriDataSource should fail early for any unsupported scheme with exception (like "UnsupportedProtocolException").

**Comment by ojw28** [comment]
Got it. What's the actual specific exception that DefaultHttpDataSource ends up throwing in this case? I mean, if it throws its own UnsupportedProtocolException type exception, that's not particularly confusing.

We did used to do exactly what you suggested, but we moved away from that approach because it's possible to use `java.net.URL.setURLStreamHandlerFactory` to allow `DefaultHttpDataSource` to support arbitrary http-like protocols such as icy, and people rely on that behavior. See for example `https://github.com/google/ExoPlayer/issues/1003`.

One option would be to explicitly throw an UnsupportedProtocolException specifically for udp, I guess, although I'm not sure it's really worth the effort.

**Comment by gpinigin** [comment]
in case of DefaultHttpDataSource
```
Internal track renderer error.
	 com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://@239.1.17.83:1234
	at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
         at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
         at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
         at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
         at android.os.Handler.dispatchMessage(Handler.java:98)
         at android.os.Looper.loop(Looper.java:136)
         at android.os.HandlerThread.run(HandlerThread.java:61)
         at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.HttpDataSource$HttpDataSourceException: Unable to connect to udp://@239.1.17.83:1234
         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:193)
         at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
         at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:727)
         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
         at java.lang.Thread.run(Thread.java:841)
     Caused by: java.net.MalformedURLException: Unknown protocol: udp
         at java.net.URL.<init>(URL.java:182)
         at java.net.URL.<init>(URL.java:125)
         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.makeConnection(DefaultHttpDataSource.java:332)
         at com.google.android.exoplayer.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:191)
         at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135) 
         at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:727) 
         at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209) 
         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
         at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
         at java.lang.Thread.run(Thread.java:841) 
```

URLConnection throws `java.net.MalformedURLException` for any unknown or not-registered protocols.


in case of OkHttpDataSource
```
com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: url == null
        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:263)
        at com.google.android.exoplayer.SampleSourceTrackRenderer.maybeThrowError(SampleSourceTrackRenderer.java:149)
        at com.google.android.exoplayer.ExoPlayerImplInternal.incrementalPrepareInternal(ExoPlayerImplInternal.java:283)
        at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:205)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.os.HandlerThread.run(HandlerThread.java:61)
        at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
     Caused by: com.google.android.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected IllegalArgumentException: url == null
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:222)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.IllegalArgumentException: url == null
        at okhttp3.Request$Builder.url(Request.java:121)
        at com.google.android.exoplayer.ext.okhttp.OkHttpDataSource.makeRequest(OkHttpDataSource.java:263)
        at com.google.android.exoplayer.ext.okhttp.OkHttpDataSource.open(OkHttpDataSource.java:156)
        at com.google.android.exoplayer.upstream.DefaultUriDataSource.open(DefaultUriDataSource.java:135)
        at com.google.android.exoplayer.extractor.ExtractorSampleSource$ExtractingLoadable.load(ExtractorSampleSource.java:727)
        at com.google.android.exoplayer.upstream.Loader$LoadTask.run(Loader.java:209)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at java.lang.Thread.run(Thread.java:841)
```

**Comment by ojw28** [comment]
Hm. How about we do the following:

1. Default to httpDataSource as we do currently.
1. If the open call fails, we're using the httpDataSource *and* the protocol that we're trying to open with isn't `http`, throw an exception that indicates the protocol might be unsupported (and wraps the original exception, so that a caller can inspect it if they want).

**Pull request closed without merging**
