### PR TITLE
Added setWakeMode implementation

### PR DESCRIPTION
**Pull request by JonathanImperato**
Added setWakeMode implementation that follows defalt MediaPlayer setWakeMode method implementation.

### CODE REVIEW

**Comment by JonathanImperato** [comment]
I signed it

**Comment by ojw28** [comment]
I don't think this code does anything, since the lock is never acquired...

I'm also not convinced such a feature is necessary. What would you use it for, and why would you need the ability to pick the mode (even if a lock is necessary, wouldn't there always be a single "correct" mode to be using)?

**Comment by ojw28** [comment]
Assigning to @andrewlewis because he may know about what wake locks are held anyway during playback (e.g. by the underlying `AudioTrack`), and what the possible use cases for `MediaPlayer.setWakeMode` are.

**Comment by andrewlewis** [comment]
@JonathanImperato Is this related to #5536? Perhaps you could share your findings if you discovered a way to stop the process getting killed in the background.

I think #930 is still accurate regarding what wake locks are held by the system. I'll also follow up with the framework team to get more information about the reasoning behind including this in the framework player's API. It may be that it's just provided via the player API so that it can be acquired/released automatically depending on the state.

**Comment by JonathanImperato** [comment]
> I don't think this code does anything, since the lock is never acquired...
> 
> I'm also not convinced such a feature is necessary. What would you use it for, and why would you need the ability to pick the mode (even if a lock is necessary, wouldn't there always be a single "correct" mode to be using)?

Sorry for the late answers.
I thought about adding this feature because it easier for the user to create wakelock if they are managed by the library, also because some do not even know what WakeLocks are.

> @JonathanImperato Is this related to #5536? Perhaps you could share your findings if you discovered a way to stop the process getting killed in the background

I am sorry but it is not.



> I think #930 is still accurate regarding what wake locks are held by the system. I'll also follow up with the framework team to get more information about the reasoning behind including this in the framework player's API. It may be that it's just provided via the player API so that it can be acquired/released automatically depending on the state.

I think that is the idea.

**Comment by tonihei** [comment]
Based on the discussion above and the linked issues it seems that we are not planning to provide a method to acquire the wake lock because it's either done automatically by the system audio components or needs to be done by the app for very specific purposes. 

I'll close for now. If you see a specific issue that needs to be solved, it's probably better to file a bug report or feature request first to simplify discussing independent of a concrete pull request.

**Comment by andrewlewis** [comment]
I've filed #5846 as I think there's value in handling acquiring/releasing the wake lock based on player state, but it will probably look different to this PR (I'm not sure yet that there is value in specifying a mode for the wake lock, for example).

**Pull request closed without merging**
