### PR TITLE
Manually set up the Widevine L3 Workaround

### PR DESCRIPTION
**Pull request by emircanpekyurek**
some content (possibly DRM based) gives an error. When securityLevel is manually set to L3, the player continues to play. I haven't a sample video

### CODE REVIEW

**Comment by icbaker** [comment]
I'm not sure I understand how this change is better than just calling `FrameworkMediaDrm#setPropertyString()` after you've constructed it.

Would you be able to offer a bit of context for how you intend to use this change?

**Comment by emircanpekyurek** [comment]
drm init:
```
val mediaDrm = FrameworkMediaDrm.newInstance(DRM_SCHEME).also {
            if (forceWideVineL3) it.setPropertyString("securityLevel", "L3")
        }
```

This code works fine but is deprecated:
```
        return DefaultDrmSessionManager(DRM_SCHEME, mediaDrm!!, drmCallback, null, true)
```

The current code is as follows. It gives an crash when I use it :

```
DefaultDrmSessionManager.Builder()
                .setUuidAndExoMediaDrmProvider(DRM_SCHEME) { mediaDrm!! }
                .setKeyRequestParameters(null)
                .setMultiSession(true)
                .build(drmCallback)
```

Contains private mediaDrm in FrameworkMediaDrm. setPropertyString is called from this variable. this may be the reason

**Comment by icbaker** [comment]
Are you saying that you're able to avoid the crash when using the `DefaultDrmSessionManager.Builder` by using the change you've proposed in this PR? Can you explain exactly what that looks like?

Regarding the crash: This is only a guess, since without the stacktrace & clear repro steps it's impossible to be sure, but I wonder if it would be fixed if you use `ExoMediaDrm.AppManagedProvider` - I think with your existing code there's a risk that the `mediaDrm` instance gets completely released.

Debugging crashes is a better fit for an issue rather than a PR - so if you want us to look deeper into the crash you're seeing can you open a new issue?

**Comment by emircanpekyurek** [comment]
erasable

**Pull request closed without merging**
