### PR TITLE
Fix nullptr when playing HLS streams with AAC audio

### PR DESCRIPTION
**Pull request by RikHeijdens**
This pull request fixes the following nullpointer:

```
12-15 14:26:59.053 865-1381/com.google.android.exoplayer.demo E/ExoPlayerImplInternal: Internal runtime error.
                                                                                       java.lang.NullPointerException: Attempt to read from field 'com.google.android.exoplayer.extractor.RollingSampleBuffer com.google.android.exoplayer.extractor.DefaultTrackOutput.rollingBuffer' on a null object reference
                                                                                           at com.google.android.exoplayer.extractor.DefaultTrackOutput.configureSpliceTo(DefaultTrackOutput.java:189)
                                                                                           at com.google.android.exoplayer.hls.HlsExtractorWrapper.configureSpliceTo(HlsExtractorWrapper.java:159)
                                                                                           at com.google.android.exoplayer.hls.HlsSampleSource.readData(HlsSampleSource.java:302)
                                                                                           at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:178)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:579)
                                                                                           at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:473)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                           at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                           at android.os.Looper.loop(Looper.java:145)
                                                                                           at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                           at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
12-15 14:26:59.083 865-865/com.google.android.exoplayer.demo V/BitmapFactory: DecodeImagePath(decodeResourceStream3) : res/drawable-xxhdpi-v4/ic_media_pause.png
12-15 14:26:59.083 865-865/com.google.android.exoplayer.demo E/EventLogger: playerFailed [5.02]
                                                                            com.google.android.exoplayer.ExoPlaybackException: java.lang.NullPointerException: Attempt to read from field 'com.google.android.exoplayer.extractor.RollingSampleBuffer com.google.android.exoplayer.extractor.DefaultTrackOutput.rollingBuffer' on a null object reference
                                                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:246)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                at android.os.Looper.loop(Looper.java:145)
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61)
                                                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40)
                                                                             Caused by: java.lang.NullPointerException: Attempt to read from field 'com.google.android.exoplayer.extractor.RollingSampleBuffer com.google.android.exoplayer.extractor.DefaultTrackOutput.rollingBuffer' on a null object reference
                                                                                at com.google.android.exoplayer.extractor.DefaultTrackOutput.configureSpliceTo(DefaultTrackOutput.java:189)
                                                                                at com.google.android.exoplayer.hls.HlsExtractorWrapper.configureSpliceTo(HlsExtractorWrapper.java:159)
                                                                                at com.google.android.exoplayer.hls.HlsSampleSource.readData(HlsSampleSource.java:302)
                                                                                at com.google.android.exoplayer.SampleSourceTrackRenderer.readSource(SampleSourceTrackRenderer.java:178)
                                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.feedInputBuffer(MediaCodecTrackRenderer.java:579)
                                                                                at com.google.android.exoplayer.MediaCodecTrackRenderer.doSomeWork(MediaCodecTrackRenderer.java:473)
                                                                                at com.google.android.exoplayer.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:431)
                                                                                at com.google.android.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:213)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:98) 
                                                                                at android.os.Looper.loop(Looper.java:145) 
                                                                                at android.os.HandlerThread.run(HandlerThread.java:61) 
                                                                                at com.google.android.exoplayer.util.PriorityHandlerThread.run(PriorityHandlerThread.java:40) 
```

The nullpointer seems to be related to discontinuities in the stream.

Any feedback is appreciated, CLA has been signed.

### CODE REVIEW

**Comment by ojw28** [comment]
I don't think this is a correct fix (I think it would just hang the playback in the buffering state forever, which is arguably worse than playback failing). Happy to be proven wrong though. Do you have a test stream and/or steps to reproduce the issue?

**Comment by RikHeijdens** [comment]
I was indeed not sure if this was the best way to fix this, however this definitely works.
I'll have to check tomorrow if I can share the stream with you, I guess that I can send it privately to your Google mail address?

**Comment by ojw28** [comment]
Well, it'll definitely fix the crash. If it's also allowing playback to proceed successfully, I'd hazard a guess that there's actually something wrong in the HLS stream you're providing.

**Comment by RikHeijdens** [comment]
I agree that there is probably something wrong with the stream itself, however we also tested the stream on a couple of other devices and players. We tested it on Firefox and Chrome on Linux using the video tag and they would play the stream fine. Also AVPlayer on iOS had no problem with playback of the stream. However Chrome on Android did crash when we would play the stream. I'm not sure what Chrome on Android uses for playback, though.

For this reason I think we should try to handle the error in the stream, if there is any.

I'm currently waiting on permission to send you the stream. I'll send it to you as soon as I have permission.

**Comment by ojw28** [comment]
I  disagree that we should handle incorrect streams because other players do so. I think I'll write a blog post about this at some point, but fundamentally it seems to me that the reason so many invalid streams exist in the first place is because other player implementations have done this. You end up in a pattern where:

1. Someone writes a specification for a stream format.
1. Someone produces a bad stream that doesn't adhere to the format.
1. Someone makes a player that plays the bad stream.
1. Other players are updated to also play the bad stream based on the "player X plays this" argument.

The end result is that:

- All players contain a whole bunch of messy workarounds to handle various types of badly formatted streams. Not only is this hard to maintain, but it degrades the efficiency with which these players can play correctly formatted streams because the executing code has to check for all these conditions.
- The specification that was originally defined is no longer an accurate reflection of reality. It therefore becomes more difficult for someone to implement a new player based on the specification and expect it to actually work with the majority of streams.

This clearly isn't good for the video ecosystem, in general, and I wish all players would stop accepting workarounds for badly formatted streams in order to fix it.

**Comment by RikHeijdens** [comment]
I just sent you an email with the stream and a couple of steps on how to reproduce the issue.
Please check it out and get back to me, if the stream is in fact incorrect I'll close the PR.

**Comment by ojw28** [comment]
Some of the chunks in the stream provided randomly don't contain any video (or declare a video stream in their program map tables). At best that's highly irregular. IMO the provider should fix the streams to ensure that each chunk contains both audio and video.

**Pull request closed without merging**
