### PR TITLE
fix(playlist): always call onCompletion when moving media sources

### LINKED ISSUE #5125: [PR offer] Always call onCompletion in ConcatenatingMediaSource.moveMediaSource
### Issue description
In `moveMediaSource` method in `ConcatenatingMediaSource` class, [at this line](https://github.com/google/ExoPlayer/blob/r2.9.0/library/core/src/main/java/com/google/android/exoplayer2/source/ConcatenatingMediaSource.java#L365), when there's actually no source to move (current and new index are the same), the `onCompletion` action is **not** invoked:

```java
if (currentIndex == newIndex) {
    return;
}
```

That is somehow a different behavior than e.g. `removeMediaSourceRange`, where completion callback is invoked right away when there's nothing to remove.

Also, that forces callers to always check for this special scenario, basically requiring a wrapper around this specific operation.

Would you consider a PR changing `moveMediaSource` behavior, so that it always calls completion callback?

We understand this can be considered a breaking change in API, as client code in its own logic may rely on this *missing invocation*. Maybe you could make the new behavior as an opt-in, like an additional method signature on `ConcatenatingMediaSource`, e.g. `moveMediaSource(int currentIndex, int newIndex, @Nullable Runnable actionOnCompletion, bool alwaysComplete)`.

Thanks for your attention

### Reproduction steps
Not Applicable

### Link to test content
Not Applicable

### Version of ExoPlayer being used
2.9.0

### Device(s) and version(s) of Android being used
Not Applicable

### A full bug report captured from the device
Not Applicable

### PR DESCRIPTION
**Pull request by BrainCrumbz**
Closes #5125

### CODE REVIEW

**Comment by GiuseppePiscopo** [comment]
I'm ok with my commits being contributed to this project.

**Comment by BrainCrumbz** [comment]
Next time we'll have to keep an eye on commit author (it's not enough to use it's public email, the same registered on Google CLA).

**Comment by tonihei** [comment]
Looks good, thanks!

**Comment by ojw28** [comment]
This was merged in the commit ref'd above. We're experimenting with a new way of syncing internal/external changes, and didn't get it quite right on this PR, which is why it's not showing as merged.

**Pull request closed without merging**
