### PR TITLE
build libvpx with NDK r16

### PR DESCRIPTION
**Pull request by alexcohn**
A minimal workaround to have libvpx built with NDK r16.

### CODE REVIEW

**Comment by alexcohn** [comment]
I cannot understand what could the problem be with CLA.

**Comment by ojw28** [comment]
Have you signed it using the same email address as you're pushing this under? Thanks!

**Comment by alexcohn** [comment]
> *Have you signed it using the same email address as you're pushing this under?*

Oops, GitHub had a wrong alias listed as the primary mail. Now it should be better.

**Comment by alexcohn** [comment]
Hi @ojw28, should I open a new PR to resolve the  clash with CLA?

**Comment by ojw28** [comment]
Probably, unless you can find a way to change the author of the commit in this PR.

**Comment by alexcohn** [comment]
> *change the author of the commit*

I have changed the primary email on the github to be my gmail, also the

**Comment by ojw28** [comment]
I think it's the author of the commit that's relevant. If I pull this and look at the git log I see: 
```
commit 1025e60de897e7c5fa8da2e1483cb1a2b931f21d (HEAD -> alexcohn-dev-v2)
Author: Alex Cohn <alexc@viber.com>
Commit: Alex Cohn <alexc@viber.com>
Remove the notice that NDK <= version 15c is required for VP9
```
And I don't see a signed CLA for that email address.

**Comment by alexcohn** [comment]
If there is some queer AI that cannot verify my GitHub account, I will probably give up this idea to push this one line into the official repo. I have already wasted too much time fighting the system, and the fix will too soon become irrelevant because the next NDK r17 will deprecate **gcc** toolchain.

**Comment by alexcohn** [comment]
*author of the commit that's relevant*

Oops, that's SourceTree to blame. Will fix.

**Pull request closed without merging**
