### PR TITLE
issue 5550

### PR DESCRIPTION
**Pull request by johnshazhu**
stream reached end but still read data

### CODE REVIEW

**Comment by ojw28** [comment]
I don't think this change is doing the right thing. If result is `RESULT_NOTHING_READ` or `RESULT_NOTHING_READ` then the contents of `inputBuffer` aren't valid.

**Comment by johnshazhu** [comment]
I signed it!

**Comment by johnshazhu** [comment]
> I don't think this change is doing the right thing. If result is `RESULT_NOTHING_READ` or `RESULT_NOTHING_READ` then the contents of `inputBuffer` aren't valid.

The result is RESULT_NOTHING_READ and inputBuffer.isEndOfStream is ture, in this condition it will keep read data and can't finish play correctly.

**Comment by ojw28** [comment]
The value of `isEndOfStream` isn't meaningful if the result is `RESULT_NOTHING_READ`.

**Comment by ojw28** [comment]
Closing because this doesn't appear to be doing the correct thing.

**Pull request closed without merging**
