### PR TITLE
Exoplayer LinearBlockMode support

### PR DESCRIPTION
**Pull request by bany2000**
add interface for exoplayer queueInputLinearBlockBuffer for  MediaCodec.LinearBlockMode in MediaCodecAdapter.java

### CODE REVIEW

**Comment by andrewlewis** [comment]
@bany2000 Please fix the CLA issues. We can't look at the code until that's sorted.

Assigning @christosts as he's investigated the new linear block APIs. Thanks!

**Comment by bany2000** [comment]
i have a CLA , but check failed ,so how to fix CLA issues.

**Comment by bany2000** [comment]
@googlebot I signed it!

**Comment by christosts** [comment]
Hi,

Thanks for this pull-request. May I ask how you plan to integrate this in your app?

To my knowledge, the MediaCodec can work in block mode only when the MediaCodec is in asynchronous mode. The MediaCodedAdapter interface purpose is to hide these details and offer a uniform MediaCodec API to the ExoPlayer. Therefore, exposing the linear block semantics to MediaCodecAdapter is somewhat conflicting with the interface's purpose. For example, it doesn't really fit having LinearBlock methods on the SynchronousMediaCodecAdapter; you should not even be able to use LinearBlocks when MediaCodec is in synchronous mode.

In some prototype code I had written at some point, all LinearBlock operations where internal to the AsynchronousMediaCodecAdapter. The AsynchronousMediaCodecAdapter was modified so that dequeueInputBuffer()/getInputBuffer()/queueInputBuffer would be modified to work with LinearBlocks instead. For example

- dequeueInputBuffer() returns the MediaCodec's available input buffer index (communicated via the callback) 
- getInputBuffer() returns a ByteBuffer that is wrapping a LinearBlock (you can have a separate LinearBlock per input buffer index, or a shared LinearBlock and BytBuffer pointing to areas of the shared buffer)
- queueInputBuffer queues the linear block (calls getQueueRequest() on the MediaCodec etc)

Would you consider this as an approach to your task?

**Comment by bany2000** [comment]
@christosts thanks for your suggestion, my app is broadcast tv. we use exoplayer to play tv ,Linearblock object create from android_media_tv_tuner.cpp not MediaCodec.obtain().we insert every video linearblock into SampleQueue.MediacodecRender read linearblock from sampleQueue and queue linearblock to mediacodec. Therefore  i need MediaCodedAdapter interface to transmit linearBlock to mediacodec.
          I agree your point that exposing the linear block semantics to MediaCodecAdapter is somewhat conflicting with the interface's purpose, but if not  exposing the linear block interface , i donot know how to implement my task. Could you help to provide some suggestion?

**Comment by christosts** [comment]
> We insert every video linearblock into SampleQueue.MediacodecRender read linearblock from sampleQueue and queue linearblock to mediacodec. Therefore i need MediaCodedAdapter interface to transmit linearBlock to mediacodec.

I assume you have made more changes, especially when the MediaCodecRenderer is reading from the sample queue
[here](https://github.com/google/ExoPlayer/blob/release-v2/library/core/src/main/java/com/google/android/exoplayer2/mediacodec/MediaCodecRenderer.java#L1235). Do you plan to share those changes too as a pull-request or not? How is your app setting up the MediaCodecRenderer to use the AsynchronousMediaCodecAdapter?

**Comment by bany2000** [comment]
@christosts i have summit my whole modifycation for linearblock,please help to review
Exoplayer LinearBlockMode support #8829

**Comment by christosts** [comment]
I am closing this pull-request as this has now moved to #8829

**Pull request closed without merging**
