### PR TITLE
Add amlogic avc decoder to eos flush workaround list

### PR DESCRIPTION
**Pull request by wendong-li**
A workaround for issue #2120

### CODE REVIEW

**Comment by wendong-li** [comment]
I signed it!

**Comment by wendong-li** [comment]
@ojw28 

This is same as pull request https://github.com/google/ExoPlayer/pull/2121, but created using my personal account. Would you review again? Sorry for any confusions this may cause.

**Comment by ojw28** [comment]
Thanks! I will get this merged into V2 as well.

**Comment by wendong-li** [comment]
Thanks @ojw28

**Pull request merged**
