### PR TITLE
Restore the flow of Transport Stream packets if synchronisation is lost

### PR DESCRIPTION
**Pull request by algrid**
For some reason TsExtractor can get a TS packet with wrong length and all the following packets become shifted by several bytes which completely breaks the video playback. This code restores the synchronisation if it's possible.

See: https://github.com/google/ExoPlayer/issues/90

### CODE REVIEW

**Comment by algrid** [comment]
I signed it!

**Comment by sreenadhkondru** [comment]
For me this issue surfaced only when using UDP as the transport. When a TS packet sent by the server is spread across two UDP packets, and one of the UDP packets is lost (which happens quite often since UDP is a lightweight unreliable transport) the TSExtractor goes out of sync. An incomplete TS packet rather than being discarded is fed with wrong bytes from another TS packet.

On the server side the fix is to set the UDP payload packet size to a multiple of 188 bytes ( I set it to 7*188 = 1316 bytes). That way even if a UDP packet gets lost, we do not end up with an incomplete TS packet. This worked for me and I never got the issue with TSExtractor again.

On the client side I tested the fix by Algrid, and it works even If the server is not configured to send UDP packets of consistent size. But I would prefer the UDPDatasource code to be refactored to catch such packet loss exceptions and throw the exception to the extractor which in turn would take the necessary steps in discarding  incomplete data.

**Comment by algrid** [comment]
In my case it fixed problems with MPEG2 TS over HTTP.

**Comment by ojw28** [comment]
I believe we've fixed this in `dev-v2`, [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/src/main/java/com/google/android/exoplayer2/extractor/ts/TsExtractor.java#L180), so closing this.

**Pull request closed without merging**
