### PR TITLE
pcm24LE->16 needs to skip the first byte (lower) for a channel, not the last (higher)

### PR DESCRIPTION
**Pull request by drhill**

### CODE REVIEW

**Comment by ojw28** [comment]
Hmm. I'm not sure about this. I have a 24-bit WAV sample that played fine with the code how it was, and is basically white noise after this change. Are you certain this change is correct, and have you tested it on some sample of your own?

**Comment by ojw28** [comment]
Sample: http://download.naimlabel.com/test/30803470-8b73-43fa-a29b-570964d7eef7.aspx

**Comment by drhill** [comment]
Yep, I only questioned it after testing and having loud white noise on my end which is now fixed.  You can test with the samples I gave you before.  I know mediainfo says it, but are your sample is actually Little Endian?  I know mine were Little Endian.  I've also read that pcm24 can be packed (http://wiki.multimedia.cx/?title=PCM)  but haven't seen that with my files.

**Comment by ojw28** [comment]
Yeah, I gave yours a try. I'm pretty sure the sample is little endian. I don't think it would have played correctly before this change if this were not the case. It's possible there's an off-by-one error in the Wav extractor for the 24-bit case, or something like that.

**Comment by ojw28** [comment]
Right, there's a "pad byte" at the start of the data chunk in WAV, which we're probably not skipping properly.

**Comment by ojw28** [comment]
Urgh, ignore me, there isn't. It's probably something like that though. I'll investigate!

**Comment by ojw28** [comment]
NB - There was a bug in WavExtractor that was causing data to be read from the wrong place. Will push a fix shortly. So all is good!

**Comment by drhill** [comment]
Ok.  Good to know.  Thanks!

**Pull request merged**
