### PR TITLE
 CastPlayer bug fixes for issues/4168

### PR DESCRIPTION
**Pull request by mkaflowski**
Couple bug fixes for issue:
[https://github.com/google/ExoPlayer/issues/4168](https://github.com/google/ExoPlayer/issues/4168)
Mostly wrong currentWindowIndex.

### CODE REVIEW

**Comment by tonihei** [comment]
Thanks for moving to the dev branch :) 

I'll wait for @AquilesCanta to have a closer look. But just in general, there seem to be some formatting-only changes (mostly indentation). Can you revert these and use our original code style?

**Comment by mkaflowski** [comment]
Ok, I will do that. I have used auto formatting in Android Studio. Are there any settings in Studio to use your code style?

**Comment by tonihei** [comment]
You can try using https://github.com/google/styleguide and import intellij-java-google-style.xml. Untested though. 

For the general guidelines, please refer to the [Google Java style guide](https://google.github.io/styleguide/javaguide.html) and some [AOSP specifics](https://source.android.com/setup/contribute/code-style). Or just copy whatever the rest of our code is doing ;)

**Comment by mkaflowski** [comment]
Thank you :) I have used intellij-java-google-style.xml but there are still some differences so I changed the rest by myself. I will make new pull request.

**Pull request closed without merging**
