### PR TITLE
Added eac3 test assets and cases

### PR DESCRIPTION
**Pull request by ybai001**
-- Added one EAC3 mp4 asset and related test case.
-- Added one EAC3 fragmented mp4 asset and related test case.

### CODE REVIEW

**Comment by ybai001** [comment]
Don't know why system indicates I login as my private account: baiyanning@gmail.com. Will create a new one.

**Comment by andrewlewis** [comment]
@ybai001 Is there a way to fix the CLA check on your side, or should we verify this manually? Thanks.

**Comment by ybai001** [comment]
> @ybai001 Is there a way to fix the CLA check on your side, or should we verify this manually? Thanks.

@andrewlewis, thanks. I asked our CLA manger to add my GitHub "no reply" email to list but it seems that it doesn't work. I unchecked my "private email" option and will create a new pull request to check whether it can solve this issue. You have helped me to manually verified several times so that I hope I can solve this issue this time. :)

**Comment by ybai001** [comment]
@andrewlewis, I created a new pull request and it can pass verification: https://github.com/google/ExoPlayer/pull/6949

Close this one.

**Pull request closed without merging**
