### PR TITLE
CastPlayer bug fixes for issues/4168

### PR DESCRIPTION
**Pull request by mkaflowski**
Couple bug fixes for issue:
[https://github.com/google/ExoPlayer/issues/4168](https://github.com/google/ExoPlayer/issues/4168)
Mostly wrong currentWindowIndex.

### CODE REVIEW

**Comment by dachev** [comment]
Are there plans to merge this one? The extension has limited utility without these fixes.

**Comment by AquilesCanta** [comment]
@dachev, as mentioned in #4168, there are some violations of the player interface which means we cannot pull as it is. I'll check if there is any specific change that may be worth picking up.

**Comment by marcin-adamczewski** [comment]
@AquilesCanta What are the plans for fixing it? Unfortunately, the Cast extension is really useless with these bugs. I think you should prioritise it.

**Comment by AquilesCanta** [comment]
We are working on a custom receiver app using our own communication protocol, so we'll be able to ensure close to end-to-end control. The new app should replace the existing components. Please be patient. I cannot provide any timelines.

**Comment by mkaflowski** [comment]
> @AquilesCanta What are the plans for fixing it? Unfortunately, the Cast extension is really useless with these bugs. I think you should prioritise it.

You can use fixed class for now. I have implemented them in HybridMediaPlayer lib if you need example.

**Comment by ojw28** [comment]
We're working on revamping the cast extension to resolve the issues that exist with the current iteration. This should happen relatively soon, so I don't think it's a good use of time to merge fixes to the current version in the meantime. Marking as wontmerge, but will leave the pull request around until the revamped version lands.

**Comment by tonihei** [comment]
Closing because it was marked as "won't merge"

**Pull request closed without merging**
