### PR TITLE
Fix issue 426 - send messages to dead thread. 

### PR DESCRIPTION
**Pull request by MaTriXy**
issue https://github.com/google/ExoPlayer/issues/426

### CODE REVIEW

**Comment by ojw28** [comment]
Please style this code in the same way as the rest of the code base. It's very difficult to review it when virtually every line has changed due to application of a different code style.

**Comment by MaTriXy** [comment]
Sorry - i thought apply the code formatting fixed it.. 
Doing a revert now.

**Comment by ojw28** [comment]
Hm. This doesn't prevent the message in all cases, although probably catches most occurrences. I'll have a think.

**Comment by MaTriXy** [comment]
Hi, 
I can't kill the handler from where we are but i can avoid sending messages when the tread is dead. 
This way messages are not sent when not needed.

**Comment by thomas-mann** [comment]
What about this pull request? I have also issues with sending messages to a dead thread. 
It happens when you're starting multiple streams in a short period of time. For example selecting the same video multiple times in a listview. 
For clearance: Every click releases the current exo player instance and creates a new one with the specific streaming url.

**Comment by ojw28** [comment]
The only issue this causes is a warning in the logs. There are no user facing issues related to this warning. For now, I think we're ok doing nothing until we have time to think about a complete fix.

**Comment by ojw28** [comment]
This is fixed in a more correct way in the [2.x.x experimental branch](https://github.com/google/ExoPlayer/tree/dev-2.X.X-experimental). We're not planning to take a fix for 1.x, since the issue is largely benign.

**Pull request closed without merging**
