### PR TITLE
Pause/resume a single download #4860

### PR DESCRIPTION
**Pull request by AleksanderMielczarek**
This PR adds possibility to pause/resume single download (#4860). Please take a look and decide whether this is correct approach, if so I'll add tests.

### CODE REVIEW

**Comment by AleksanderMielczarek** [comment]
I signed it!

**Comment by AleksanderMielczarek** [comment]
Implementation seems to be working ok. Added some tests.

**Comment by erdemguven** [comment]
Thanks for the pull request. Actually we're doing some major changes on DownloadManager which breaks this change. The good news is we're planning the add this feature as well. I'll check if we can a least partially use this code.

**Comment by volkansahin45** [comment]
Will it be ready at next release? @erdemguven

**Comment by meenukrishnamurthy** [comment]
Is this feature merged in the current release??

**Comment by erdemguven** [comment]
We're working on a similar change currently. There is no certain date or release it will be available but I can say sometime soon.

**Comment by AleksanderMielczarek** [comment]
@erdemguven Do you have any updates?

**Comment by ojw28** [comment]
The ability to stop and resume an individual download is supported in `2.10.0` with `DownloadManager.setStopReason`. In the normal case of using a `DownloadService`, you should use `DownloadService.sendSetStopReason` or `DownloadService.buildSetStopReasonIntent`. The `2.10.0` release should happen next week (and we've already made a `2.10.0-alpha2` available that contains this functionality.

**Pull request closed without merging**
