### PR TITLE
Make FLV video seekable by a seekMap.

### PR DESCRIPTION
**Pull request by shenwill**
Tested and works fine.

### CODE REVIEW

**Review by kim-vde — COMMENTED** [review]
Could you add some tests with a sample stream? You can find examples [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/test/java/com/google/android/exoplayer2/extractor/mp3/Mp3ExtractorTest.java) and [here](https://github.com/google/ExoPlayer/blob/dev-v2/library/extractor/src/test/java/com/google/android/exoplayer2/extractor/mp3/IndexSeekerTest.java). Thanks!

**Comment by kim-vde** [comment]
Any news for the tests?

**Comment by kim-vde** [comment]
Is this ready to be reviewed? I see that some parts of the code are commented.

**Comment by shenwill** [comment]
Just checked in. Now it's ready to be reviewed. Thanks.

**Comment by kim-vde** [comment]
I cleaned the pull request and merged the part about seeking in FLV files.

I didn't merge the part about parsing the frame rate and adding it to the format because:
- It does not seem related to FLV seeking.
- It is not clear what is the advantage of doing that.
- The frame rate might be variable so I would avoid adding it the the format (which is generally constant).
If you still want this part to be merged, please open a new pull request and explain what is the intention.

**Pull request merged**
