### PR TITLE
fix durationUs error caused by different track timescale

### PR DESCRIPTION
**Pull request by XiaoLongTX**
I have a video that contains two tracks. The timescale of one track is 1000, the timescale of the other track is 48000, and the movieTimescale is 1000. As a result, the video time I get is 48 times the real video time.

### CODE REVIEW

**Comment by XiaoLongTX** [comment]
@googlebot I fixed it.

**Comment by XiaoLongTX** [comment]
@googlebot I fixed it.

**Comment by XiaoLongTX** [comment]
@googlebot I fixed it.

**Comment by icbaker** [comment]
Thanks for the PR - I can see you've signed the CLA but as the bot says, there are still commits in the PR with other author email addresses.

If these are other people they need to also sign the CLA and comment here explicitly agreeing to contribute these changes.

**Comment by XiaoLongTX** [comment]
@icbaker 
Sorry, when I submitted this time, I used the company's computer and the mailbox was the company's email. This email could not receive the verification email from Google, so I was unable to signed the CLA. I changed the git email and resubmitted.

**Pull request closed without merging**
