### PR TITLE
Exo player in recyclerview

### PR DESCRIPTION
**Pull request by ralphpina**
This is the same work as in google/ExoPlayer#1982

> I recently implemented ExoPlayer inside a RecyclerView and I could not find any examples, and very little (none?) documentation on how to do this. I have taken my implementation and added it to the Demo application.

### CODE REVIEW

**Comment by nominalista** [comment]
Have you noticed and do you know why some items hangs on loading video after scroll for example to the bottom?

**Comment by ralphpina** [comment]
I haven't noticed any loading issues. I tested it on a HTC ONE with L and Nexus 6 with N. However... there could be a host of possible issues:

1) Hardware is having issues with the instantiation and killing of all the video players as you scroll?
2) Network loading issues?

There's bound to be a lot of issues in certain devices and network conditions which we can't code around. However, I'm sure there's some optimizations that could be made to minimize them...

**Comment by nominalista** [comment]
I tested it on Nexus 6P with N. [Here](https://youtu.be/7ayO-wtlGaM) you find video and [here](http://pastebin.com/xw2UG6VY) are logs. 

I suppose it's not related to network issues, but as you may see while scrolling some ViewHolder which are reused have not stopped video.

**Comment by ralphpina** [comment]
Yeah... there seems to be a race condition with my implementation. I can take a looksie if this is something people think would be helpful as part of the demo app.

**Comment by nominalista** [comment]
It would be great if you look at it. As you said before, it's very hard to find some examples with video in RecyclerView.

**Comment by eneim** [comment]
@ralphpina @Nominalista I have completed my major release of [my implementation for the same idea](https://github.com/eneim/toro). Can you guys take a look at it? Comparing to the old v2, it is ways simpler I believe ... :D.

**Comment by tonihei** [comment]
Closing because this is just an example for using ExoPlayer in a RecyclerView and slightly out of date.

**Pull request closed without merging**
