### PR TITLE
Added option to ImaAdsLoader to skip all ads in group 

### PR DESCRIPTION
**Pull request by sediger**
Modeling after YouTube which skips all ads in group when user skips current ad.

### CODE REVIEW

**Comment by sediger** [comment]
@googlebot I signed it!

**Comment by sediger** [comment]
@googlebot I signed it!

**Comment by chadacious** [comment]
> Modeling after YouTube which skips all ads in group when user skips current ad.

IMHO, this is a great, and sometimes necessary, option for the IMA extension.

**Comment by icbaker** [comment]
Closing all PRs on this deprecated project. We are now unable to merge PRs from here. If you would like us to consider this change again please file a new PR on the media3 project: https://github.com/androidx/media/pulls

**Pull request closed without merging**
