### PR TITLE
Compatible video coding with mpeg1video in Mp4Extractor

### PR DESCRIPTION
**Pull request by xufuji456**
Hello, guy of developers. I found that it doesn't support mpeg1video in Mp4Extractor. Therefore, I add mpeg1video which name is m1v to make it compatible.

Here is the testing video:[https://drive.google.com/file/d/116_x0RwRYEAcCDnQyOlTHMHqPe67D3-J/view?usp=sharing](url)

### CODE REVIEW

**Comment by kim-vde** [comment]
The link to the test video is broken. Could you please fix it? If you're unable to share test content publicly, please send it to dev.exoplayer@gmail.com using subject "Issue #8257".

**Comment by xufuji456** [comment]
Maybe you could use this link to test: https://drive.google.com/file/d/116_x0RwRYEAcCDnQyOlTHMHqPe67D3-J/view

**Comment by kim-vde** [comment]
Out of curiosity, do you know how the video is rendered? Does the test device you use have an mpeg1 video decoder?

**Comment by xufuji456** [comment]
@kim-vde I apologize for not being clear about the situation. Take into consideration the compatibility, We extend the video SoftDecoder with FFmpeg. Therefore, we decode the mpeg1 video by the decoder of mpeg1video, maybe it couldn't work on MediaCodec.

**Pull request merged**
