### PR TITLE
Improved minimumUpdatePeriod when not present

### PR DESCRIPTION
**Pull request by tidoemanuele**
when minimumUpdatePeriod is missed the default values is not zero but -9223372036854775807

### CODE REVIEW

**Comment by ojw28** [comment]
The line of code you're changing is not intended to catch the case in which minimumUpdatePeriod is missing. It's intended to catch the case where the minimum update period is explicitly set to 0.

What behavior are you seeing when minimumUpdatePeriod is missing? Do you see constant refreshes? I think the correct fix would be to never refresh in this case, since as per the spec:

> If this attribute is not present it indicates that the MPD does not change.

Please clarify. Thanks!

**Comment by tidoemanuele** [comment]
yes I see constant mpd requests when minimumUpdatePeriod is missing

**Comment by ojw28** [comment]
Ok. I think the correct fix is to ensure the manifest refresh isn't scheduled if minimumUpdatePeriod is missing.

**Comment by tidoemanuele** [comment]
I got your point but in the case of dash live stream I'd like to refresh the manifest periodically, any suggestions?

**Comment by ojw28** [comment]
Fix your stream to comply with the DASH specification?

**Comment by ojw28** [comment]
I don't think we can merge this. It explicitly goes against the DASH specification, since omitting minimumUpdatePeriod is defined to mean that the manifest does not change, which implies that we should not be re-requesting it. I'll merge a separate fix to not re-request in this case.

**Pull request closed without merging**
