### PR TITLE
Calculate frame rate for Matroska

### PR DESCRIPTION
**Pull request by Nemiroff**
Added calculation of the frame rate for Matroska

### CODE REVIEW

**Comment by Nemiroff** [comment]
> @googlebot I signed it!

**Comment by ojw28** [comment]
I don't think it's accurate to say that this is a frame-rate. It might be equal to the frame-rate in some (possibly many) cases, but I don't think it's true in the general case.

**Comment by Nemiroff** [comment]
defaultSampleDurationNs is Number of nanoseconds (not scaled via TimestampScale) per frame
1000000000ns = 1 second

**Comment by ojw28** [comment]
> Number of nanoseconds (not scaled via TimestampScale) per frame **('frame' in the Matroska sense - one Element put into a (Simple)Block).**

This is discussed in some detail on [this page](https://gitlab.com/mbunkus/mkvtoolnix/-/wikis/Wrong-frame-rate-displayed).

**Pull request closed without merging**
