### PR TITLE
Return REMOVED_AD_GROUP if adGroups is empty

### PR DESCRIPTION
**Pull request by kaan-celen**

### CODE REVIEW

**Comment by kaan-celen** [comment]
https://github.com/google/ExoPlayer/issues/10817

**Comment by marcbaechinger** [comment]
Thanks for your PR. Can you clarify what you are trying to achieve? Because if the ad playback state is empty and no ad group has been removed, I don't think we should return `REMOVED_AD_GROUP`. 

You can look at `playbackAdState.adGroupCount` to check whether the group is empty. If you try to get an ad group by an index that does not exist, it seems correct to me to throw an exception.

**Comment by kaan-celen** [comment]
> Thanks for your PR. Can you clarify what you are trying to achieve? Because if the ad playback state is empty and no ad group has been removed, I don't think we should return `REMOVED_AD_GROUP`.
> 
> You can look at `playbackAdState.adGroupCount` to check whether the group is empty. If you try to get an ad group by an index that does not exist, it seems correct to me to throw an exception.

Hi Marc, thanks for your reply.
I experience a crash in our app which inside the exoplayer flow.
I do have checks for on my codebase but `getAdGroup` method is also used in `PlaybackStatsListener.findBestEventTime` and cause crashes. I did check my advert data and it looks fine and reported bug looks like cannot be resolved by my codebase.

Here is the crash log and I also raise an issue on github and linked to this PR
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.google.android.exoplayer2.source.ads.AdPlaybackState.getAdGroup(AdPlaybackState.java:485)
       at com.google.android.exoplayer2.Timeline$Period.getAdGroupTimeUs(Timeline.java:728)
       at com.google.android.exoplayer2.analytics.PlaybackStatsListener.findBestEventTime(PlaybackStatsListener.java:322)
       at com.google.android.exoplayer2.analytics.PlaybackStatsListener.onEvents(PlaybackStatsListener.java:247)
       at com.google.android.exoplayer2.analytics.AnalyticsCollector.lambda$setPlayer$1$AnalyticsCollector(AnalyticsCollector.java:142)
       at com.google.android.exoplayer2.analytics.-$$Lambda$AnalyticsCollector$uX7qombvbhfllBfrArZ4fy72Fso.invoke(-.java:6)
       at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.iterationFinished(ListenerSet.java:272)
       at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java:224)
       at com.google.android.exoplayer2.util.ListenerSet.handleMessage(ListenerSet.java)
       at com.google.android.exoplayer2.util.-$$Lambda$ListenerSet$gt28PMFfhLXGfIVY4v7eP9kmalg.handleMessage(-.java:2)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:223)
       at android.os.Looper.loop(Looper.java:317)
       at android.app.ActivityThread.main(ActivityThread.java:7942)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)
```

**Comment by tonihei** [comment]
As @marcbaechinger pointed out above, this change may prevent the crash itself, but doesn't really make sense on a logical level. The actual fix should be somewhere else and if you can provide detailled reproduction steps to help us debug, please comment on https://github.com/androidx/media/issues/743.

**Pull request closed without merging**
