### PR TITLE
Making easier to set the playClearSampleWithoutKeys to renderers

### PR DESCRIPTION
**Pull request by szaboa**
Pull request for the following issue: #5421

### CODE REVIEW

**Comment by rgrk11** [comment]
@ojw28, please also add setter method for `MediaCodecSelector`, because I would like to use `MediaCodecSelector.DEFAULT_WITH_FALLBACK` with `DefaultRenderersFactory`.

**Comment by ojw28** [comment]
@szaboa - Looks great; thanks! Fancy adding the selector @rgrk11 mentions whilst you're at it?

**Comment by szaboa** [comment]
Sure, I can add the selector as well.

**Comment by szaboa** [comment]
@ojw28 , @rgrk11 
Added setter for `MediaCodecSelector` used in `buildVideoRenderers `and `buildAudioRenderers`.

**Comment by ojw28** [comment]
This got merged in the commit above. Apologies that this PR didn't get properly marked as being merged. We have a system to commit changes internally first, and it got a bit confused in this case.

**Pull request closed without merging**
