### PR TITLE
Adding ascending sort of TrackGroup

### PR DESCRIPTION
**Pull request by yoobi**
This enhancement match with this issue https://github.com/google/ExoPlayer/issues/7709

This is my first time contributing to a project, feel free to tell me if I did something wrong.

I'm comparing the bitrate of the `TrackGroup` as it works for both Audio and Video.

I've also notice that the original `TrackGroup` from `trackGroups.get(groupIndex);` is always 0, maybe I could delete the first loop over the `groupIndex`

### CODE REVIEW

**Comment by yoobi** [comment]
@googlebot I signed it!

**Comment by yoobi** [comment]
It seems I've made a mistake, when selecting the format (ie: 250p) it is not switching to it but to another one.

**Comment by ojw28** [comment]
In terms of making this API generally useful, could you design it so that the caller can pass any `Comparator<Format>`, rather than just providing a boolean option to enable one specific type of sorting? This would also be useful for other use cases, for example sorting text tracks based on their language.

**Comment by yoobi** [comment]
You're right, I'll use a `Comparator<Format>` instead, problem is I don't see where to do the sort.
My previous problem was when I changed the order in `TrackSelectionView` the array was sorted and then displayed in the UI, but behind when I was clicking on a `Format` it was using the old array.
Or Should I pass the `Comparator` to `MappedTrackInfo` and make the sorting there ?

**Comment by yoobi** [comment]
I've been doing the sorting (inside `MappingTrackSelector`) but the issue is once it is all sorted, it no longer goes into `onTracksChanged`, and I've got no error. Do you have any idea why?

**Comment by ojw28** [comment]
Obsoleted by https://github.com/google/ExoPlayer/pull/7798

**Pull request closed without merging**
