### PR TITLE
add pgs subs to simpleexoplayer

### PR DESCRIPTION
**Pull request by drhill**
moving pgs subtitle code derived from ffmpeg from my app into simpleexoplayer.

### CODE REVIEW

**Comment by ghost** [comment]
LGPL violation.

**Comment by jbkempf** [comment]
Agreed, it cannot be imported into Apache2 code.

**Comment by ojw28** [comment]
We don't plan to merge this change. It would, however, be helpful if more information than just "violation" could be provided. Specifically, where does the code originate from? Thanks!

**Comment by jbkempf** [comment]
It is a copy paste of the libavcodec PGS decoder.

**Comment by ojw28** [comment]
Thanks for the information.

@drhill - Please be aware that under the terms of the CLA, any contributions must be original works. Details of any third party licenses or restrictions must be included in the submission. You can follow the personal/corporate CLA links [here](https://github.com/google/ExoPlayer/blob/release-v2/CONTRIBUTING.md) for more details. Thanks!

**Comment by drhill** [comment]
No problem.  I thought I had all citations in it but must have got lost before a commit when I was cleaning up formatting.  Also, copy paste would imply actually copying and pasting without change.  It's derivative and translated to java while removing some superfluous steps to decode the format in java.

Would another PR request for just handling ImageCues (and thus a new ImageCues class) in SimpleExoPlayerView.java and exo_simple_player_view.xml be taken?

**Comment by ghost** [comment]
> It's derivative and translated to java 

Apparently you don't know how Copyright works.

**Comment by drhill** [comment]
You are right I should have had the licensing at the top and it wouldn't have slipped my mind that this wouldn't have been something to submit.  I had it in my app that only I use a long time ago and just quickly threw it together for this thus forgot about LGPL.

My response wasn't about you.  Copy and paste would never work when switching languages (hence translation, meaning derivative).  In reality there is basically only one way to decode this that isn't flowering it up and changing variable/function names in order to not match what was already written, but that would be disingenuous.  But go ahead and be that person on the internet that needs to make a point when "You are missing the copyright notice from pgssubdec.c which states LGPL that invalidates this from submission" would have sufficed.

**Comment by ghost** [comment]
> In reality there is basically only one way to decode this that isn't flowering it up and changing variable/function names in order to not match what was already written, but that would be disingenuous.

Changing code until nobody recognizes it anymore still does not remove the copyright from the original code.

No wonder development of these Google things is so fast...

**Comment by drhill** [comment]
Apparently you have some recognition problems.  I didn't say code changing.  I said there was only one way to write this.  Start from scratch and it still comes out the same and someone could say you played with variable names and whitespace.  Or you could say "there is no java implementation, I'll adapt the c implementation and leave everything as close to the original as possible".  Forgetting the attribution was a mistake.  

Getting all uppity with an attitude in a case where someone is using a license to squat on code that is akin to patenting the ability to drive a car in a straight line isn't necessary.  Great that they wrote the code for others.  They just followed a basic spec and put out a basic implementation first while limiting others from following it in the future.

**Comment by ojw28** [comment]
Just to clarify: The default position for this project is that we only accept original contributions where the contributor (or their company in the case of the corporate CLA) owns the copyright/IP. Although the CLA makes provision for "submitted on behalf of a third-party" contributions, we are unlikely to accept such contributions in practice, even if the source and licenses are accurately stated. We will definitely not accept contributions of any work covered by LGPL/GPL.

@wm4 - If you could refrain from making drive-by comments about "Google things" based on a pull request that was not created by us, that had a signed CLA, and that we at no point indicated we were going to merge, that would be nice. Thanks for your compliment regarding our speed of development, however!

**Comment by ghost** [comment]
> Getting all uppity with an attitude in a case where someone is using a license to squat on code that is akin to patenting 

Just pointed it out. I'm not the author of this code, have seen other rampant copyright violations of ffmpeg code (and related projects) by random companies, and last but not least, I couldn't care less about this. However, it did seem that you were justifying copy & paste because there's "only one way to write it", and that converting it to another language is "not copy & paste". Well, just be aware that converting some code to another language and then forgetting about copyright is still a copyright violation.

> If you could refrain from making drive-by comments about "Google things" based on a pull request that was not created by us, 

Well, at the same day this PR was pointed out in ffmpeg-devel, someone linked to another google project where some ffmpeg code was copy & pasted without attribution, and this one was already in the main git repo/branch. (The one who linked it was supposedly the author of the ffmpeg code.) But again, I don't care etc. and didn't attempt to verify it, just pointing it out. I would conclude that accidental copyright violation is possibly rampant, but again, my sample size might be too small.

In the end I'm not your or ffmpeg's lawyer. I just thought I'd point this out before this were to be carelessly merged - which according to you wasn't going to happen, so everything is fine.

> Thanks for your compliment regarding our speed of development, however!

This too was just an empty assumption which I didn't verify.

**Comment by ojw28** [comment]
We are of course grateful for you pointing out the issue with this pull request, and please continue to do this if you see other pull requests that you believe are similarly problematic. This is valuable information. Please include a reference to the original source when doing so, so that we can take a look.

Regarding the latter point: Making drive-by comments insinuating poor development practices is not pointing anything out. It's at best unnecessary, particularly if you don't care and haven't taken time to verify your statements. Since you have no issue with this particular project, this doesn't seem like the correct place to be making such points, either. Thanks!

**Pull request closed without merging**
