### PR TITLE
CEA608 changes to pass Sarnoff tests

### PR DESCRIPTION
**Pull request by peddisri**
1. NTSC parity and validity bit check added
2. process_cc_data_flag check added
3. PAINT ON mode support added
4. Fixed line alignment issues for multi-line text
5. Fixed issue of dropping too many duplicate control commands
6. Fix for showing CC1 even if other channels are selected
7. Filtering out TEXT and XDS content
8. Fix for missing whitespaces when italic or other mid-row formatting
is used
9. Fix for NTSC Deleted tests of sarnoff
10. Log illegal control codes instead of throwing exception

### CODE REVIEW

**Comment by ojw28** [comment]
As noted on previous pull requests, if you can describe the change in the form of 10 bullet points, it should really be split into 10 pull requests, or at least 10 commits within a single pull request so the changes can be looked at in isolation. It's really hard to review changes where everything is just squashed together like this.

**Comment by peddisri** [comment]
okie :-)

**Comment by zsmatyas** [comment]
Splitting this change into smaller change sets:
https://github.com/google/ExoPlayer/pull/5075

**Comment by zsmatyas** [comment]
Second pull request:
https://github.com/google/ExoPlayer/pull/5147 (fixes for paint-on mode)

**Comment by ojw28** [comment]
Is this an accurate reflection of the current state for merging these changes:

1. NTSC parity and validity bit check added **merged**
1. process_cc_data_flag check added
1. PAINT ON mode support added **merged**
1. Fixed line alignment issues for multi-line text **merged**
1. Fixed issue of dropping too many duplicate control commands
1. Fix for showing CC1 even if other channels are selected
1. Filtering out TEXT and XDS content
1. Fix for missing whitespaces when italic or other mid-row formatting is used **probably fixed via afc19bf6dba83e49b5261fe7db78311b803af0e2, so no longer needed?**
1. Fix for NTSC Deleted tests of sarnoff
1. Log illegal control codes instead of throwing exception

(2) and (6) sound relatively trivial to get merged next (although I didn't look at which code changes those correspond to). Possibly (7) and (10) as well?

**Comment by zsmatyas** [comment]
Yes, that state seems to be correct. I have a list of all commits with comments what changes can be squashed in what order, so the next ones on my list are:
5. Fixed issue of dropping too many duplicate control commands
6. Fix for showing CC1 even if other channels are selected
7. Filtering out TEXT and XDS content  + 10. squashed into it as they are the same topic

8. Is already fixed with the commit you linked.

2. is implemented in CeaUtil.java, so the order of the commits is not important.

**Comment by zsmatyas** [comment]
Last merged Line alignment fix is https://github.com/google/ExoPlayer/pull/5201

Now added fix for duplicated control code checks:
https://github.com/google/ExoPlayer/pull/5355
This should fix https://github.com/google/ExoPlayer/issues/3860

**Comment by zsmatyas** [comment]
Handling channel bit: https://github.com/google/ExoPlayer/pull/5390

**Comment by ojw28** [comment]
Is it just (9) and (10) from the original list at the top of this pull request that are still outstanding? Are we close enough that this pull request can be closed? Thanks!

**Comment by ojw28** [comment]
Closing this since most of it has landed elsewhere. If there are pending changes (e.g. for (9) and (10)), I would assume they will come as separate pull requests). Thanks for your help!

**Pull request closed without merging**
