### PR TITLE
Remove fully-qualified name

### PR DESCRIPTION
**Pull request by mofneko**
The fully-qualified name has already been imported.

### CODE REVIEW

**Comment by andrewlewis** [comment]
Please could you make a pull request to the `dev-v2` branch instead?

**Comment by mofneko** [comment]
Oops, Sorry.
See: https://github.com/google/ExoPlayer/pull/2787

**Comment by mofneko** [comment]
Oops, Sorry.
See: https://github.com/google/ExoPlayer/pull/2787

**Comment by mofneko** [comment]
Oops, Sorry.
See: https://github.com/google/ExoPlayer/pull/2787

**Comment by mofneko** [comment]
Oops, Sorry.
See: https://github.com/google/ExoPlayer/pull/2787

**Comment by mofneko** [comment]
Oops, Sorry.
See: https://github.com/google/ExoPlayer/pull/2787

**Pull request closed without merging**
