### PR TITLE
Adds bintray release plugin

### PR DESCRIPTION
**Pull request by xrigau**
What the title says

BTW this has been released to bintray POW https://bintray.com/novoda/maven/exoplayer/view

### CODE REVIEW

**Comment by xrigau** [comment]
woops wrong repo!

Sorry

**Comment by xrigau** [comment]
Just FYI we've released the exoplayer library under the novoda account to jcenter so that we can use it from a centralised point

**Comment by xrigau** [comment]
#fridayAwkwardMoments

**Comment by xrigau** [comment]
BTW something worth considering of from google's side :tada:

**Comment by ojw28** [comment]
Heh. Yes, we're going to do this. There's a tracking issue here: https://github.com/google/ExoPlayer/issues/28

**Comment by xrigau** [comment]
ah cool! thanks for pointing it :+1:

**Pull request closed without merging**
