### PR TITLE
Added proper dpad seekbar positioning

### PR DESCRIPTION
**Pull request by bigexxx**

### CODE REVIEW

**Comment by ojw28** [comment]
Could you clarify what is not "proper" about dpad seeking if you just make the SeekBar focusable?

**Comment by bigexxx** [comment]
yep, just make seekbar focusable and workable

**Comment by ojw28** [comment]
Are you saying just making it focusable is sufficient, or are you saying that this pull request is required? If so, what does this pull request achieve that just making the SeekBar focusable (and nothing else) does not?

**Comment by bigexxx** [comment]
no, i additionally added seekEndedAction Runnable and setOnKeyListener on progressBar for handling dpad keycodes, after clicking right or left, dpad is seeked and posted delayed action to commit changes to player

**Comment by ojw28** [comment]
@andrewlewis Is working on making some other changes to the seek bar, which likely mean this change wont be necessary.

**Comment by ojw28** [comment]
The dev branch has a new `TimeBar` class now. Is this change still needed, or does that behave in the desired way? If it is still needed, the implementation should probably be moved from `PlaybackControlView` into `DefaultTimeBar`?

**Comment by andrewlewis** [comment]
The `DefaultTimeBar` we'll push shortly (probably today) implements similar timeout behavior to this PR: after pressing the left/right directional buttons the seek will occur after a timeout, unless the user presses the center/enter button which causes the seek to happen immediately.

**Pull request closed without merging**
