### PR TITLE
Enable flac to seek without SEEKTABLE

### PR DESCRIPTION
**Pull request by sjnyag**
Pull request for #1808.
In the case flac has no SEEKTABLE, search seek position by libflac function.

### CODE REVIEW

**Comment by botaydotcom** [comment]
Unfortunately this pull request cannot be merged because it's not quite correct. When I used it locally to seek around the sample provided on #1808, it usually ended up at a different place than the seek position (some time very far from the correct position).

I have implemented this feature anyway, so this is not needed anymore. Thank you very much for the effort.

**Comment by sjnyag** [comment]
Thank you very much for review.
Sorry. I agree with your opinion. I did not verify with streams.
I am looking forward to the release of this feature.

**Comment by ojw28** [comment]
Support was added in https://github.com/google/ExoPlayer/commit/972304f16b0f5aba21439785b4c9e2b831e364f6.

**Comment by sjnyag** [comment]
Many thanks for your support.

**Pull request closed without merging**
