### PR TITLE
merge  Dev v2 rtp  into  Dev v2 rtsp

### PR DESCRIPTION
**Pull request by arlimm318**
My project needs to support both RTP and RTSP,But I see that the RTP and RTSP support libraries int two branches ,What should I do with these 2 branches?Do I need to merge two branches into one?That would be complicated.
I need a branch that supports both RTP and RTSP.

### CODE REVIEW

**Comment by ojw28** [comment]
It's unclear what this is trying to do. Note however we do not accept pull requests directly into the release branch.

**Comment by arlimm318** [comment]
Is there a branch that supports both RTP and RTSP?I couldn't find a branch of exoplayer that could support both.Can you Help me？


| |
李亚
|
|
15628816381@163.com
|
签名由网易邮箱大师定制
On 10/16/2019 20:49，Oliver Woodman<notifications@github.com> wrote：

Closed #6518.

**Comment by ojw28** [comment]
We do not support either RTP or RTSP at this point, sorry. If you want to try and take the two pending pull requests and get them working together, you'll need to do this in your own branch for now.

**Comment by arlimm318** [comment]
OK，Thank you very much.


| |
李亚
|
|
15628816381@163.com
|
签名由网易邮箱大师定制
On 10/23/2019 15:54，Oliver Woodman<notifications@github.com> wrote：

We do not support either RTP or RTSP at this point, sorry. If you want to try and take the two pending pull requests and get them working together, you'll need to do this in your own branch for now.

**Pull request closed without merging**
