### PR TITLE
Added comment: ExoPlayer video playback requires API level 16

### PR DESCRIPTION
**Pull request by dturner**

### CODE REVIEW

**Comment by dturner** [comment]
Reference Issue #86

**Comment by ojw28** [comment]
Happy to pull this, but you'll need to sign the CLA as per (here)[https://github.com/google/ExoPlayer/blob/master/CONTRIBUTING.md].

**Comment by dturner** [comment]
No problem signing the CLA. Does it change anything that I work for Google:
donturner@google.com?

On Tue, Apr 14, 2015 at 12:04 PM, ojw28 <notifications@github.com> wrote:

> Happy to pull this, but you'll need to sign the CLA as per (here)[
> https://github.com/google/ExoPlayer/blob/master/CONTRIBUTING.md].
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/google/ExoPlayer/pull/395#issuecomment-92770312>.
>



-- 
+44 (0) 7939 287199
@donturner <http://www.twitter.com/donturner>
LinkedIn profile <http://www.linkedin.com/profile/view?id=5331958>

**Comment by ojw28** [comment]
See internal IM. Thanks!

**Pull request closed without merging**
