### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by peddisri**
Hi,

These are some of the patches created to work around issues in Fire TV Gen1 Box  & Fire TV Stick,  and Fire OS 4 based Kindle Tablets. 

Let me know your opinion.

Regards,
Srikanth

### CODE REVIEW

**Comment by peddisri** [comment]
Hi,

Amazon has signed CLA as a corporation.

Regards,
Srikanth

**Comment by ojw28** [comment]
a2e2626 - This doesn't look like a good idea. It'll generate a significant amount of garbage because it's creating String objects every time a video frame is rendered. This overhead is incurred even if logging is disabled for the module. We already expose sufficient information for playback analytics via the EventLogger interfaces that many components expose. So I don't think we want to merge this.

245c745 - Happy to take this as an individual pull request, since it looks pretty isolated. Not keen on having an AmazonQuirks class though. Let's just put the special case directly into MediaCodecUtil. We already have other special cases in that class (e.g. blacklisting of known broken decoders).

5d52107, 45d0eef - These look too involved for it to be worth taking them, given we'll have to maintain the code going forward. Amazon can upgrade these devices to resolve the underlying issues.

**Comment by ojw28** [comment]
Amazon probably have a group that you need to become a member of for you to be linked against the corporate CLA.

**Comment by peddisri** [comment]
I am already part of that group. Please verify at your end.

**Comment by ojw28** [comment]
I think your Amazon address is part of that group, but you're using a Lab126 address that isn't. You need to get the Lab126 address added to the group, or use your Amazon address on GitHub. The bot does verify corp CLA signers, so you should be able to reply `I signed it!` once this is resolved.

**Comment by peddisri** [comment]
Thanks. Will fix the email id in the next pull request containing only https://github.com/google/ExoPlayer/commit/245c7457f8dfa95d1f23c72cda323c5a4f9ba74f

**Comment by ojw28** [comment]
Sounds good to me. I'll close this one, in that case!

**Pull request closed without merging**
