### PR TITLE
Parse stz2 Atoms during mp4 extraction.

### PR DESCRIPTION
**Pull request by natez0r**

### CODE REVIEW

**Comment by natez0r** [comment]
I signed it! Twitter

**Comment by ojw28** [comment]
Any update on the CLA? Thanks.

**Comment by natez0r** [comment]
we signed a new one with an internally controlled mailing list, I am a member of that list. Not quite sure what else we'd need to do?

**Comment by ojw28** [comment]
I signed it!

**Comment by ojw28** [comment]
You're showing up on the CLA signers list for me now, so if you say you signed it again, I think the bot will be happy! Give it a try.

**Comment by natez0r** [comment]
I signed it!

**Comment by natez0r** [comment]
thanks!

**Comment by natez0r** [comment]
should i attempt to create a PR for the dev-v2 branch?

**Comment by ojw28** [comment]
Nope, we'll take care of that. Thanks!

**Pull request merged**
