### PR TITLE
FrameworkSampleSource with FileDescriptor

### PR DESCRIPTION
**Pull request by Nezz**
As discussed in #246

### CODE REVIEW

**Comment by Nezz** [comment]
Should I submit this to master or dev?

**Comment by ojw28** [comment]
It'll need submitting into dev. You'll also need to sign the appropriate CLA before we can merge the change. See:

https://github.com/google/ExoPlayer/blob/master/CONTRIBUTING.md

Thanks!

**Comment by CCorrado** [comment]
Was this PR not included in r.2.4.1 ? Looking for the proper way to use FileDescriptor (instead of a URI) with ExoPlayer, this is a perfect solution. Not seeing "FrameworkSampleSource" or another MediaSource implementation that takes in a FD instead of URI.

**Comment by ojw28** [comment]
`FrameworkSampleSource` is not part of ExoPlayer V2, since we removed all our dependencies on Android's `MediaExtractor` API. It's probably best if you file a new issue/question explaining what you're actually trying to do (in terms of what the use case is, rather than "I want to use a FileDescriptor"). There may well be an easy alternative or better way of doing whatever you're trying to do.

**Pull request closed without merging**
