### PR TITLE
Add a method to support clearing all download manager helpers on DownloadService class

### PR DESCRIPTION
**Pull request by dongvanhung**
This method is necessary in case your application supports downloading for multiple users on the same application and the same device.

For example, 
Login with account A, downloads content A, then logout. 
Login with account B,  downloads content A (same as content that downloaded on account A).
After switched to account B, we must to reset the `DownloadManager` to avoid multiple users use the same download folder.
```
DownloadManager?.release()
DownloadManager = null
```
In the case we call `DownloadManager?.release()`, if we do not clear all `downloadManagerHelpers`, `DownloadService` can not be started again.

But now `downloadManagerHelpers` is private and we cannot reset it in inherited subclasses. Therefore, it is necessary to have a method to reset it.

Please review and approve this PR.
Thank you.

### CODE REVIEW

**Comment by dongvanhung** [comment]
@marcbaechinger 
Can you please review this ? Thank you !

**Comment by donny9095** [comment]
@marcbaechinger @tonihei 
We want to this method too. Can you please add this method to the next release version ?

**Comment by devno44** [comment]
No one wants to review this ?

**Comment by icbaker** [comment]
Closing all PRs on this deprecated project. We are now unable to merge PRs from here. If you would like us to consider this change again please file a new PR on the media3 project: https://github.com/androidx/media/pulls

**Pull request closed without merging**
