### PR TITLE
fix second seek sync position for live

### PR DESCRIPTION
**Pull request by zenxu88**
For the case the first segment number is not 0 based, getSegmentCount() could be smaller than segmentNum.
This will make seek always pick the first keyframe. To fix this, we use getLastSegmentNumber() instead.

### CODE REVIEW

**Comment by ojw28** [comment]
@tonihei - Does it make sense for you to take a look at this, given you were adjusting some related logic in `DefaultDashChunkSource` for DASH-LL recently? Thanks!

**Comment by tonihei** [comment]
Please sign the CLA before we can have a look at your PR. Thanks!

**Comment by tonihei** [comment]
Closing because we didn't receive a CLA. We'll submit a fix for the problem ourselves instead.

**Comment by zenxu88** [comment]
@tonihei I finally got CLA through my company email. However it seems you have applied a fix already?

**Comment by tonihei** [comment]
Yes, sorry. It seemed worth a fix, so we went ahead and applies our own fix to the problem. Thanks for looking into the CLA anyway :) Maybe it becomes useful in the future.

**Pull request closed without merging**
