### PR TITLE
Aus subtitle

### PR DESCRIPTION
**Pull request by MrtDolphin0128**
Customized Engine for Australian Subtitles in UPD streaming mode

### CODE REVIEW

**Comment by andrewlewis** [comment]
If you just want to share this code somewhere, I suggest making a fork and pushing your changes there (#7747).

If the goal is to contribute it to ExoPlayer we need more information (#7746) and it also looks like this was probably sent from the wrong branch or something else has gone wrong given that a lot of other changes are included in the pull request in addition to https://github.com/google/ExoPlayer/pull/7749/commits/44d2cb83ae798077aaecad5ce7650b9fae36c195.

**Comment by icbaker** [comment]
Moving the implementation/PR-specific discussion here, to avoid spamming #7220.

From https://github.com/google/ExoPlayer/issues/7746#issuecomment-673926423: 
> The library calls upon an external dependency, CCExtractor https://github.com/CCExtractor/ccextractor , per the advise by @icpaker.

To clarify, I advised you **not** to use CCExtractor and to implement this support in pure Java instead (https://github.com/google/ExoPlayer/issues/7746#issuecomment-673387453):
>  I think we're unlikely to accept a PR that implements this using CCExtractor when we weigh up the maintenance cost we'd be introducing against the benefits it brings.

To reiterate my statement from https://github.com/google/ExoPlayer/issues/7746#issuecomment-673425769, we will accept:

1. A high quality PR implementing this support in pure Java, with no external dependencies. Or,
2. A clear, reasoned argument with plenty of technical detail that convinces us a pure Java implementation for this is impossible, and a high quality PR adding an extension to support this using native dependencies (see the [vp9 extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/vp9) as an example).
    * Note: It's going to be challenging to convince us of this, since we already have pure Java support for what I believe are very similar subtitle formats embedded in MPEG transport streams (e.g. CEA-608).

If you want to add support for this format to ExoPlayer I'd strongly urge you to follow path 1 and do it in pure Java. If you're planning to take path 2 I'd suggest you convince us with the argument **before** spending any more time on coding/implementation, because as I say it's going to be hard to convince us.

**Comment by a4x4kiwi** [comment]
@icbaker What can we do to progress the Australian Subtitles. @MrtDolphin0128 is developing this for us. Do you have any guidance to him to make the code compliant to assist with progressing the code into the project?

**Comment by icbaker** [comment]
I'm going to close this as we're not going to accept it in its current form. Please re-open (or file a new one) with an approach that follows either of my two suggestions above.

**Pull request closed without merging**
