### PR TITLE
Allow passing of HlsPlaylistParser to HlsMediaSource.

### PR DESCRIPTION
**Pull request by natez0r**
Also create helper method in HlsMasterPlaylist to allow the copying of
the playlist to another, but with the variants reordered based on a
passed comparator. Also added an implementation of HlsPlaylistParser
which will reorder the variants returned.

Another approach to #3293

### CODE REVIEW

**Comment by natez0r** [comment]
@ojw28 was this more in line with what you were hoping for?

**Comment by ojw28** [comment]
Yes, except with `ReorderingHlsPlaylistParser` in your codebase, rather than inside the ExoPlayer library directly. Is it flexible enough for you to do what you need to do?

**Comment by natez0r** [comment]
I believe it will be. I need to test it locally now, but having some trouble building exo locally in our app (taking a bit longer than hoped)

**Comment by natez0r** [comment]
was able to get this building and tested out. this is flexible enough for us. would you like me to remove the re-ordering stuff?

**Comment by natez0r** [comment]
ok, updated

**Pull request merged**
