### PR TITLE
Added NotificationDispatcher

### LINKED ISSUE #5301: ExoPlayer manipulate notification based on Playerstate
### Issue description
How can I make the exoplayer notification dismissable when the player is paused and then make it a foreground service when it it resumed? Here are my questions:
1. https://github.com/google/ExoPlayer/issues/4256#issuecomment-388936681: How can I start a foreground service by using `startForeground` inside `onPlayerStateChanged`? Is there a way to retrieve notification object that's already constructed?
2. https://github.com/google/ExoPlayer/issues/4482#issuecomment-407088270: Can we please have the code base on the demo app changed so that we can refer that?

### Reproduction steps
IO18 audio app
https://github.com/google/ExoPlayer/tree/io18

### Version of ExoPlayer being used
latest

### Device(s) and version(s) of Android being used
Nexus 6p. API level 28

### PR DESCRIPTION
**Pull request by 0xcaff**
`NotificationDispatcher` provides an interface for delivering notifications from a `PlayerNotificationManager`. This can be used to implement a foreground service with a notification which is only pinned (non-dismissable) when the player is playing.

Here's an example of using these changes to implement the desired behavior in the I/O 2018 app.

Running: https://youtu.be/ckKVB4iy5yw
Code: https://gist.github.com/0xcaff/c20e4ea226c33eb68a5cd9cbb80fbb96!

I'd make a PR for the I/O 2018 app too, except there's a bunch of stuff broken in it which I'm not sure how to fix.

Closes #5301

### CODE REVIEW

**Comment by gowthamgts** [comment]
Just for confirmation, isn't the `setOngoing` supposed to be `true` when playing, and `false` when it's not?

**Comment by 0xcaff** [comment]
The ongoing status of the notification is automatically handled by startForeground and stopForeground. Calling setOngoing isn’t needed. 

This is what the UAMP demo app does. https://github.com/googlesamples/android-UniversalMusicPlayer/blob/master/media/src/main/java/com/example/android/uamp/media/MusicService.kt

**Comment by 0xcaff** [comment]
I've integrated these changes into my app and almost everything works. In my app, the notification isn't the only consumer of the player. The player is also accessible through a binder exposed in `onBind`.

By default `NotificationDispatcher.cancel` is only called on notification dismissal when `setStopAction(null)` is not called. This means the only way for the cancellation callback to be called is to enable the stop action (and the corresponding button in the notification). Dismissing the notification triggers `STOP_ACTION` stopping the player on dismissal, which is not the desired behavior. At most, the playback should be paused, not stopped.

While it is possible to make this work by extending the notification manager, it's kinda hack-y. You'd have to use this modification, extend notification manager override `getActions` to hide the stop button and use a custom `ControlDispatcher` to disable the stop action. All this, and it only works if you don't need the stop button in the notification.

Are you open to breaking changes? Can we separate the stopping behavior and the notification cancellation behavior?

This is too hard. I want to modify the notification drawables later, so I decided it would be easier to just re-write the notification manager in my application.

Implementation: https://github.com/forte-music/android/blob/18e0eac5487ee6c39526244c531fe1af149eca4e/app/src/main/java/me/a0xcaff/forte/playback/PlayerNotificationManager.kt
Usage: https://github.com/forte-music/android/blob/18e0eac5487ee6c39526244c531fe1af149eca4e/app/src/main/java/me/a0xcaff/forte/playback/PlaybackService.kt

**Comment by 0xcaff** [comment]
Closing due to inactivity.

**Comment by ojw28** [comment]
@marcbaechinger - Could you take a look at this?

**Comment by gowthamgts** [comment]
@0xcaff: They might respond slow since it was holiday time.

**Comment by marcbaechinger** [comment]
Yes, sorry for being late.

Thanks for the pull request.

We should certainly provide a way to make the notification dismissible when the player is paused in a service. I was under the impression this works but  I certainly could miss something:

> Dismissing the notification triggers STOP_ACTION stopping the player on dismissal, 
> which is not the desired behavior. At most, the playback should be paused, not stopped.

You can set your custom action with setStopAction("your-action"). When the notification is dismissed, this action is fired which you can handle yourself. Stop is not called in this case. 

------
The current approach which I think should do the trick is the following (and obviouly not well documented). I wonder whether this is working for you.

1. Stop foreground when player is paused
Like you said, the notification can't be dismissed when attached to a service which is in foreground. So you need to call service.stopForeground(/*removeNotification*/ false) when the player is paused (you can listen for playWhenReady within the onPlaybackStateChanged of a listener to stopForegound the service.

2. playerNotificationManager.setOngoing(false)
Needs to be set to false so the notification can be dismissed.

3. playerNotificaitionManager.setStopAction(yourCustomAction)
When the notification is dismmissed and there is a stopAction, that stopAction is fired when the user dismisses the notification. If you set your own, your action is fired.

Hence you can set your custom action to replace the internal stop action. Then you can handle your custom stop action with a CustomActionReceiver and do whatever you want to do in case the user dismisses the notification.

4. Use a CustomActionReceiver to handle you custom stop action which is fired when the user dismisses the notification.

**Comment by ojw28** [comment]
Closing this PR because other changes have been merged that attempt to achieve the same thing. Please see #5301, and let's use that issue for any discussion. Thanks!

**Pull request closed without merging**
