### PR TITLE
Add test cases for iframe only with EXT-X-MAP

### PR DESCRIPTION
**Pull request by stevemayhew**
The "implicit" init segment logic in the `HlsPlaylistParser` in the original pull request for i-Frame only
support had an off by one bug.  This commit adds unit test cases to cover that bug and for validating both
explicit and implicit initialization segments.

Thanks to @marcbaechinger for fixing the bug when the original pull request was merged, just returning the favor by increasing the `HlsPlaylistParser` UT coverage a bit.

### CODE REVIEW

**Comment by stevemayhew** [comment]
I see the implicit init unit test was covered already, and pretty much matched my test.   So this commit just includes EXT-X-MAP with a BYTERANGE attribute (which a couple of our Origin partners use)

**Comment by AquilesCanta** [comment]
The title of the commit seems correct to me, but the pull request's doesn't. Should with be **with EXT-X-MAP**?

**Comment by stevemayhew** [comment]
Thanks @AquilesCanta updated title

**Comment by stevemayhew** [comment]
We've definitely got some cycles and interest in increasing the test coverage of the parsers

**Pull request merged**
