### PR TITLE
CacheKeyFactory is not used.

### PR DESCRIPTION
**Pull request by nebyan**
when I use this method with custom CacheKeyFactory it does not work properly.
Because inside of this method it is going to create CacheDataSource with default CacheKeyFactory so my custom CacheFactory not used.

### CODE REVIEW

**Comment by nebyan** [comment]
@googlebot I signed it!

**Comment by nebyan** [comment]
@googlebot I fixed it.

**Comment by ojw28** [comment]
Hi. Please could you fix the CLA issue so we can merge this? It appears you have a signed CLA, but the commit is showing as being from "TURKCELL\tcmdolgun" rather than yourself.

**Comment by nebyan** [comment]
@googlebot I fixed it.

**Comment by nebyan** [comment]
Hi @ojw28 I changed my username, email and commited. Is it ok or do I must create PR from scratch

**Comment by ojw28** [comment]
Hm, the change is still showing as being authored by "TURKCELL\tcmdolgun" here:
https://github.com/nebyan/ExoPlayer/commits/RedundantCacheKeyFactory. I think you need to make that commit appear to be authored by nebyan and/or have it use the email address you used for the CLA.

**Comment by nebyan** [comment]
Ok Im going create from scratch

**Pull request closed without merging**
